"""topoham -- Lie-Topological Graph Policies for Hamiltonian Simulation.

CPU reference implementation. Every public number this package reports is
generated by running the code (see scripts/ and the Makefile); nothing is
hard-coded. First-order Trotter evolution is computed with an exact statevector
simulator built on single-Pauli rotations, and validated against dense
``scipy.linalg.expm`` and Krylov ``expm_multiply`` references.
"""
from __future__ import annotations

__version__ = "0.1.0"

from . import (  # noqa: F401
    audit,
    commutator_graph,
    config,
    env,
    hamiltonians,
    metrics,
    pauli,
    plotting,
    policies,
    reproduce,
    runner,
    seed,
)
